"""empty message

Revision ID: edc3358b27e2
Revises: e5db0ac01933
Create Date: 2020-02-27 21:56:26.650509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc3358b27e2'
down_revision = 'e5db0ac01933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tpname', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tpname')
    # ### end Alembic commands ###
